-- Auto Mecânica Confiança — v11 core backend
-- Supabase/PostgreSQL schema for the first real end-to-end OS flow.

create extension if not exists pgcrypto;

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text,
  email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vehicles (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customers(id) on delete cascade,
  plate text,
  make text,
  model text,
  version text,
  year integer,
  km integer,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists vehicles_plate_unique
  on public.vehicles (upper(plate))
  where plate is not null and btrim(plate) <> '';

create table if not exists public.work_orders (
  id uuid primary key default gen_random_uuid(),
  number bigint generated by default as identity unique,
  customer_id uuid not null references public.customers(id),
  vehicle_id uuid references public.vehicles(id),
  status text not null default 'open'
    check (status in ('open','inspection','budget','waiting_approval','approved','in_service','ready','delivered','cancelled')),
  complaint text,
  current_km integer,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  closed_at timestamptz
);

create table if not exists public.inspection_photos (
  id uuid primary key default gen_random_uuid(),
  work_order_id uuid not null references public.work_orders(id) on delete cascade,
  phase text not null default 'entry' check (phase in ('entry','exit','service')),
  slot text not null check (slot in ('front','rear','left','right','panel','other')),
  storage_path text not null,
  required boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists inspection_photos_os_idx on public.inspection_photos(work_order_id);

create table if not exists public.budget_revisions (
  id uuid primary key default gen_random_uuid(),
  work_order_id uuid not null references public.work_orders(id) on delete cascade,
  revision integer not null default 1 check (revision > 0),
  status text not null default 'draft'
    check (status in ('draft','sent','approved','revision_requested','superseded','cancelled')),
  subtotal numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  approved_at timestamptz,
  unique(work_order_id, revision)
);

create table if not exists public.budget_items (
  id uuid primary key default gen_random_uuid(),
  budget_revision_id uuid not null references public.budget_revisions(id) on delete cascade,
  kind text not null default 'service' check (kind in ('part','service','other')),
  description text not null,
  quantity numeric(12,3) not null default 1 check (quantity > 0),
  unit_price numeric(12,2) not null default 0 check (unit_price >= 0),
  line_total numeric(12,2) generated always as (round(quantity * unit_price, 2)) stored,
  sort_order integer not null default 0
);

create table if not exists public.approval_tokens (
  id uuid primary key default gen_random_uuid(),
  budget_revision_id uuid not null unique references public.budget_revisions(id) on delete cascade,
  token uuid not null unique default gen_random_uuid(),
  expires_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists approval_tokens_token_idx on public.approval_tokens(token);

create table if not exists public.approvals (
  id uuid primary key default gen_random_uuid(),
  budget_revision_id uuid not null unique references public.budget_revisions(id) on delete cascade,
  approval_token_id uuid references public.approval_tokens(id),
  customer_name text not null,
  decision text not null check (decision in ('approved','revision_requested')),
  consent boolean not null default false,
  signature_path text,
  signature_sha256 text,
  user_agent text,
  ip_hash text,
  created_at timestamptz not null default now()
);

create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  work_order_id uuid references public.work_orders(id) on delete cascade,
  actor_user_id uuid references auth.users(id),
  actor_type text not null default 'user' check (actor_type in ('user','customer','system')),
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists activity_log_os_idx on public.activity_log(work_order_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists customers_set_updated_at on public.customers;
create trigger customers_set_updated_at before update on public.customers
for each row execute function public.set_updated_at();

drop trigger if exists vehicles_set_updated_at on public.vehicles;
create trigger vehicles_set_updated_at before update on public.vehicles
for each row execute function public.set_updated_at();

drop trigger if exists work_orders_set_updated_at on public.work_orders;
create trigger work_orders_set_updated_at before update on public.work_orders
for each row execute function public.set_updated_at();

alter table public.customers enable row level security;
alter table public.vehicles enable row level security;
alter table public.work_orders enable row level security;
alter table public.inspection_photos enable row level security;
alter table public.budget_revisions enable row level security;
alter table public.budget_items enable row level security;
alter table public.approval_tokens enable row level security;
alter table public.approvals enable row level security;
alter table public.activity_log enable row level security;

-- Pilot policies: authenticated workshop users can operate the internal app.
-- Public customer approval is NOT exposed through these tables; it goes through Edge Functions.
do $$
declare
  t text;
begin
  foreach t in array array['customers','vehicles','work_orders','inspection_photos','budget_revisions','budget_items','approval_tokens','approvals','activity_log']
  loop
    execute format('drop policy if exists authenticated_all on public.%I', t);
    execute format(
      'create policy authenticated_all on public.%I for all to authenticated using (true) with check (true)',
      t
    );
  end loop;
end $$;

insert into storage.buckets (id, name, public)
values ('oficina-evidence','oficina-evidence',false)
on conflict (id) do update set public=false;

-- Only authenticated internal users can read/write normal evidence directly.
drop policy if exists "authenticated evidence read" on storage.objects;
create policy "authenticated evidence read"
on storage.objects for select to authenticated
using (bucket_id='oficina-evidence');

drop policy if exists "authenticated evidence write" on storage.objects;
create policy "authenticated evidence write"
on storage.objects for insert to authenticated
with check (bucket_id='oficina-evidence');

drop policy if exists "authenticated evidence update" on storage.objects;
create policy "authenticated evidence update"
on storage.objects for update to authenticated
using (bucket_id='oficina-evidence')
with check (bucket_id='oficina-evidence');
