-- v11.4 Mercado Pago payment request foundation

create table if not exists public.payment_requests (
  id uuid primary key default gen_random_uuid(),
  public_token uuid not null unique default gen_random_uuid(),
  work_order_id uuid not null references public.work_orders(id) on delete cascade,
  budget_revision_id uuid references public.budget_revisions(id) on delete set null,
  receivable_id uuid references public.receivables(id) on delete set null,
  provider text not null default 'mercadopago',
  method text not null default 'pix',
  amount numeric(12,2) not null check (amount > 0),
  currency text not null default 'BRL',
  payer_email text,
  status text not null default 'draft'
    check (status in ('draft','pending','processing','approved','rejected','cancelled','expired','refunded','partially_refunded','provider_error')),
  idempotency_key uuid not null unique default gen_random_uuid(),
  provider_payment_id text,
  pix_copy_paste text,
  pix_qr_code_base64 text,
  payment_url text,
  expires_at timestamptz,
  provider_payload jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists payment_requests_provider_payment_unique
on public.payment_requests(provider,provider_payment_id)
where provider_payment_id is not null;

create index if not exists payment_requests_work_order_idx on public.payment_requests(work_order_id);
create index if not exists payment_requests_receivable_idx on public.payment_requests(receivable_id);
create index if not exists payment_requests_status_idx on public.payment_requests(status);

create table if not exists public.payment_webhook_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  provider_event_id text not null,
  resource_id text,
  event_type text,
  payload jsonb not null default '{}'::jsonb,
  processed_at timestamptz,
  created_at timestamptz not null default now(),
  unique(provider,provider_event_id)
);

drop trigger if exists payment_requests_set_updated_at on public.payment_requests;
create trigger payment_requests_set_updated_at before update on public.payment_requests
for each row execute function public.set_updated_at();

alter table public.payment_requests enable row level security;
alter table public.payment_webhook_events enable row level security;

drop policy if exists active_staff_all on public.payment_requests;
create policy active_staff_all on public.payment_requests
for all to authenticated
using (public.is_active_staff())
with check (public.is_active_staff());

drop policy if exists active_staff_all on public.payment_webhook_events;
create policy active_staff_all on public.payment_webhook_events
for all to authenticated
using (public.is_active_staff())
with check (public.is_active_staff());
